### ISSUE TITLE
Cursor is not centered horizontally in the char box or area

### ISSUE THREAD

**Issue by M3Rocket** [xornorik/SVPinView#11]
The cursor should be centered on the character horizontally, but is not.

![image](https://user-images.githubusercontent.com/3769123/43674038-00c19e5a-9782-11e8-9398-df348149e7cd.png)

**Comment by xornorik** [comment]
Yes, this issue stems from the fact that there is no way to detect a 'backspace' key unless there is already some text in the TextField. So in order to register the backspace event, I have to fill the empty field with a space character. 

I could fix this using constraints, but it seemed to be a trivial problem for the amount of work required. I will get to it eventually, but let me know if you can think of a better solution 😉.
