### ISSUE TITLE
Size of individual input

### ISSUE THREAD

**Issue by lukeirvin** [xornorik/SVPinView#26]
Is it possible to update the size of the input areas?

I can manage to get the width about accurate based on where I need to place this, but the height of each input area is too small.

**Comment by xornorik** [comment]
Hey @lukeirvin, each input area/box maintains a square shape (aspect ratio 1:1). They conform to the constraints applied to the SVPinView such that the width and height of the input area/box would be set to min(width, height) + the applied padding/margins. 

Since there is no scroll, the dimensions are limited by the width and height constraints of the SVPinView.
