### ISSUE TITLE
Interspace property is not working properly

### ISSUE THREAD

**Issue by sanjeevThapar** [xornorik/SVPinView#37]
First of all thank you for the library. I am using your library in one of my project and setting "interSpace" is not working properly. If I set a space using this property then interspacing between views goes to 0.  Could you please look into it?

**Comment by xornorik** [comment]
Hi @sanjeevThapar. I'm glad you found this library useful. 
The behaviour you are describing happens when the width of the SVPinView is less than width calculated by using properties like ```pinLength``` & ```interSpace```.

<img width="538" alt="Screenshot 2020-03-16 13 56 13" src="https://user-images.githubusercontent.com/21356007/76736988-e8ae2d00-678d-11ea-8f74-1489313fb817.png">

Will include a wrong state alert in the upcoming versions, but for now, you can fix this my ensuring that the math is right. 

Let me know if this solves your issue.

**Comment by sanjeevThapar** [comment]
@xornorik thanks for your quick response I will check it and revert.
