### ISSUE TITLE
Pinview shows "xx pasted from yy" notification on entering pin

### ISSUE THREAD

**Issue by leijdekkers** [xornorik/SVPinView#54]
Since iOS 14 the SVPinview shows a "xxx pasted from yyy" notification whenever i enter text/number into a SVPinView. Looks like the UITextField needs to be modified and disable clipboard actions. Or can this be done already? If so how?

**Comment by aKANJx** [comment]
I'd try a PR but it appears the owner doesn't accept PR since 2018. So, this is the solution:
CustomSVPinView.swift -> Remove (string == UIPasteboard.general.string) in line 454
If you're using pods, fork it and use it as a private pod. Otherwise, manually insert it into your project.

Cheers

**Comment by xornorik** [comment]
@leijdekkers Many thanks for reporting this! Apologies for the delay in response. Will put out a release with the changes suggested by @aKANJx.

@aKANJx 
Thank you for the solution! Will add your change and put out a release today. 


> I'd try a PR but it appears the owner doesn't accept PR since 2018.

Not true. I've not merged *some* of the PR's due to certain reasons, but I have merged in most of the PR's (the last release was a PR -  #42). I suppose I should resolve all of them to avoid confusion 🙂. 
Thanks again for the solution! Appreciate it!

**Comment by leijdekkers** [comment]
Thanks! It is a bit of a showstopper right now getting all these notifications when you enter a pincode! Appreciate the effort.

**Comment by leijdekkers** [comment]
When will you release an updated version fixing this issue?

**Comment by xornorik** [comment]
@leijdekkers 
Just did on CocoaPods. 
Carthage is giving me some troubles; it appears there have been some heavy changes for Xcode 12 - [more here](https://github.com/Carthage/Carthage/issues/3019#issuecomment-693302447)

If you're using CocoaPods, could you confirm if you're still getting the notification?

**Comment by xornorik** [comment]
@leijdekkers Are you using CocoaPods or Carthage?

**Comment by leijdekkers** [comment]
Just tested it and all good! No more notifications! Thanks a lot!

**Comment by xornorik** [comment]
Thant's great! Thanks for the confirmation. 🙂

**Comment by jpauljm** [comment]
Thanks, @xornorik! Sorry, I misinterpreted the PRs. I appreciate all effort you're doing creating and maintaining this useful repo.
