### ISSUE TITLE
Not working for 4 pin

### ISSUE THREAD

**Issue by himanthmaddi** [xornorik/SVPinView#8]
I have set pin length to 4 and style to underline. Then the borderline color is not working (Whatever color you set, it's showing as clear color) but it is working for 6 pin.

**Comment by xornorik** [comment]
@himanthmaddi Will investigate and update shortly. Thanks.

**Comment by xornorik** [comment]
@himanthmaddi, the issue wasn't with the borderline color, but rather the size of the pinField. The pinView calculates the size of each field based on its width; so if the pinLength is smaller and spread over a larger area, the top and bottom portions of the field were being hidden which is why you were not able to see the underline. 

I've put in a fix now which takes into consideration both the height and the width of the pinView while calculating the size of the fields. Let me know if you have more feedback. Thanks.

**Comment by himanthmaddi** [comment]
@xornorik thanks for prompt response.
